### ISSUE TITLE
If appium can attach Microsoft Edge WebDriver to a running WebView2 app?

### ISSUE THREAD

**Issue by Simmon12** [appium/appium-chromium-driver#192]
hello, I have a project that can automate a webview app.  When opening an app, a webview2 will automatically open to display the content of a URL.  Can I use appium-chromium-driver to drive the Microsoft Edge WebDriver to connect to a running webview page instead of opening a new window by default?

**Comment by KazuCocoa** [comment]
I haven't tried, but I guess yes.
`ms:edgeOptions` option as https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver may achieve that

**Comment by Simmon12** [comment]
> I haven't tried, but I guess yes. `ms:edgeOptions` option as https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver may achieve that

thanks, I'll give it a try.
