### ISSUE TITLE
Driver failed to start session with message "No matching capabilities found"

### ISSUE THREAD

**Issue by SharpQ** [appium/appium-chromium-driver#275]
Hello, 
I am using Chromium driver for some time and recently updated it from "1.2.68" to "1.3.15" version. 
After driver update, I receive error "session not created: No matching capabilities found" each time on session start. 
I didn't change any capabilities from "1.2.68" version and on that version everything works fine.
Could you advise how can I resolve this error and use latest chromium driver version? 

MacOS: 11.2.3
Appium Server: 2.2.2
Appium-Python-Client: 3.1.0
Chromium driver: 1.3.15

Driver capabilities:
 Creating session with W3C capabilities: {
   "alwaysMatch": {
     "platformName": "macOS",
     "browserName": "chrome",
     "appium:automationName": "Chromium",
     "appium:autodownloadEnabled": true
   },
   "firstMatch": [
     {}
   ]
 }

I am also attaching Appium log files:
[appium_logs.log](https://github.com/appium/appium-chromium-driver/files/14448739/appium_logs.log)

**Comment by KazuCocoa** [comment]
Yes, it looks like chrome stricted the platformName to follow w3c webdriver spec https://github.com/chromium/chromium/commit/cac9966089796326f76ffbb888244f388b2361b1
so macOS might be `mac`

**Comment by SharpQ** [comment]
> try a platformName of 'mac' instead?
Just checked and it worked. Thanks a lot!
